### ISSUE TITLE
Having problem in serving very big files

### ISSUE THREAD

**Issue by randoms** [cloudhead/node-static#113]
It seems that node-static load the whole file to memory at the begining, so when the file is very big, an error will occur.

**Comment by devTristan** [comment]
I am getting a similar error with a 2GB file.

```
buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Server.respondNoGzip (/usr/local/lib/node_modules/node-static/lib/node-static.js:337:33)
    at Server.respond (/usr/local/lib/node_modules/node-static/lib/node-static.js:352:14)
    at /usr/local/lib/node_modules/node-static/lib/node-static.js:144:22
    at Object.oncomplete (fs.js:107:15)
```

**Comment by randoms** [comment]
If you want to serve static files, [send](https://github.com/pillarjs/send) is a much better choice.

**Comment by mnpenner** [comment]
I tried serving a 4.4 GB file and got a different error:

```
RangeError: invalid Buffer length
    at RangeError (native)
    at allocate (buffer.js:81:20)
    at new Buffer (buffer.js:39:12)
    at Server.respondNoGzip (/usr/local/filewhal/node_modules/node-static/lib/node-static.js:339:33)
    at Server.respond (/usr/local/filewhal/node_modules/node-static/lib/node-static.js:354:14)
    at /usr/local/filewhal/node_modules/node-static/lib/node-static.js:93:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

My server has 2GB of memory.

**Comment by jozsi** [comment]
Same here, serving a 2GB file with 3.5GB free memory.
```
jozsi@lfa:~$ static -a 0.0.0.0 www
serving "www" at http://0.0.0.0:8080
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid typed array length
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:96:12)
    at new Buffer (buffer.js:56:12)
    at Server.respondNoGzip (/usr/lib/node_modules/node-static/lib/node-static.js:339:33)
    at Server.respond (/usr/lib/node_modules/node-static/lib/node-static.js:354:14)
    at /usr/lib/node_modules/node-static/lib/node-static.js:146:22
    at FSReqWrap.oncomplete (fs.js:82:15)
jozsi@lfa:~$ static -v
node-static 0.7.7
```

**Comment by cloudhead** [comment]
When the in-memory cache was removed, the buffer creation wasn't (https://github.com/cloudhead/node-static/pull/100) — essentially it's creating a buffer in memory now that isn't needed.

**Comment by cloudhead** [comment]
https://github.com/cloudhead/node-static/pull/180 — can't test it.
