### ISSUE TITLE
static -H is broken

### ISSUE THREAD

**Issue by waynebloss** [cloudhead/node-static#160]
I tried the header [example from the readme](https://github.com/cloudhead/node-static#example-usage) and I get the following error:

```
> static -H '{"Cache-Control": "no-cache, must-revalidate"}'
undefined:1
'{Cache-Control:
^
SyntaxError: Unexpected token '
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\Wayne\AppData\Roaming\npm\node_modules\node-static\bin\cli.js:83:46)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by waynebloss** [comment]
node-static 0.7.6

**Comment by waynebloss** [comment]
OK, it's most likely a Windows issue since when I changed it to `static -H "{""Cache-Control"": ""no-cache, must-revalidate""}"`, it worked.
