### ISSUE TITLE
Errors and warning are written to console

### ISSUE THREAD

**Issue by laino** [cloudhead/node-static#185]
``node-static`` is spamming console.error with useless stack traces when receiving "invalid" range headers and the like. It would be nice if those warning could at least be intercepted, so they can be funneled through custom logging and the like.

Maybe an "error" event, where if there are no even listeners registered the error gets printed to the console?

Currently I get a few of these every second, which makes my log files.... very spammy:

```
Request contains invalid range header:  [ '13620', '13620' ]
Error: Range request present but invalid, might serve whole file instead
    at Server.respondNoGzip (/var/volafile/app/node_modules/node-static/lib/node-static.js:300:23)
    at /var/volafile/app/node_modules/node-static/lib/node-static.js:224:18
    at FSReqWrap.oncomplete (fs.js:111:15)
```

**Comment by nhrones** [comment]
I'm getting same warnings, but only when I'm serving to Chrome-on-Android?

**Comment by andrewhodel** [comment]
This is the same issue as #212.

This is about standard output and standard error, as it is consistently request-able from any HTTP client to any HTTP server using node-static, it should not be printed to standard output or standard error.
