### ISSUE TITLE
Error: Class constructor Server cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Ravost99** [cloudhead/node-static#237]
Can't figure out how to solve this.

Code:
```javascript
"use strict"
import createServer from 'bare-server-node';
import http from 'http';
import Server from 'node-static';
//const static = require('node-static')


const bare =  createServer('/bare/');
const serve = new Server('static_folder/');

const server = http.createServer();

server.on('request', (req, res) => {
    if (bare.shouldRoute(req)) {
		bare.routeRequest(req, res);
	} else {
		serve.serve(req, res);
	}
});

server.on('upgrade', (req, socket, head) => {
	if (bare.shouldRoute(req, socket, head)) {
		bare.routeUpgrade(req, socket, head);
	}else{
		socket.end();
	}
});

server.listen({
	port: process.env.PORT || 8080,
});
```
Console:
```
(node:4115) UnhandledPromiseRejectionWarning: TypeError: Class constructor Server cannot be invoked without 'new'
    at file:///home/runner/statictest/index.mjs:8:15
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async /home/runner/statictest/index.js:3:3
(node:4115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Ravost99** [comment]
I fixed it, sorry
